### ISSUE TITLE
Version with Monix

### ISSUE THREAD

**Issue by jdegoes** [zio/interop-monix#1]
I think we should version this library with Monix.

e.g. if you're using Monix 3.0-RC3, then you pull in `interop-monix` 3.0-RC3.

We can use the micro version for backward-compatible updates within a Monix version.

Thoughts?

**Comment by mijicd** [comment]
As agreed in `ZIO/Core` gitter, we'll proceed with `vA.B.C.D` versioning scheme, `A.B.C` coming representing semantic version of a library, and `D` enumerating the patch made in interop.
