### ISSUE TITLE
Latest ZIO (1.0.1)

### ISSUE THREAD

**Issue by octavz** [zio/interop-monix#154]
Hi,
Are there any plans to upgrade this to latest ZIO version?

Thank You.

**Comment by mijicd** [comment]
@octavz Hi, sorry for late response. I will try to make this happen over the next couple of days!

**Comment by mijicd** [comment]
After a (very) long delay due to my schedule, I'm closing this issue as "won't solve". Moreover, this interop won't be supported in the future.
